#配置config服务的账号密码
spring:
 security:
  user:
    name: sparrow
    password: 123456

#注册中心配置
eureka:
  auth:
    user: sparrow
    password: 123456
  client:
    service-url:
      #TODO 生产环境中配置高可用 http://${eureka.auth.user}:${eureka.auth.password}@localhost:7001/eureka/,http://${eureka.auth.user}:${eureka.auth.password}@localhost:7002/eureka/
      defaultZone: http://${eureka.auth.user}:${eureka.auth.password}@localhost:8761/eureka/
  instance:
    #使用IP进行注册
     prefer-ip-address: true
    #配置实例的注册ID
     instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #心跳时间，即服务续约间隔时间（缺省为30s）
     lease-renewal-interval-in-seconds: 5
    #发呆时间，即服务续约到期时间（缺省为90s）
     lease-expiration-duration-in-seconds: 10