server:
  port: 8761 #启动端口
spring:
  profiles: 
    active: dev
  #应用名称
  application:
    name: sparrow-eureka

#eureka配置
eureka:
  server:
    #设置扫描失效服务的间隔时间
    eviction-interval-timer-in-ms: 20000
    enable-self-preservation: true