#服务端口
server:
  port: 8001

#config服务自身配置
spring:
  profiles:
    active: dev
  #应用名称
  application:
    name: server-config
  cloud:
    config:
      server:      
        git:         
          uri: https://github.com/Enhinck/config.git
          username: huenbin@foxmail.com
          password: 12345678
          default-label: master
          search-paths: '{application}'