#服务端口
server:
  port: 8765

#config服务自身配置
spring:
  #应用名称
  application:
    name: sparrow-admin
  profiles: 
    active: dev
  boot:
      #设置不监控某些服务
      discovery:
        ignored-services: sparrow-config,sparrow-admin
      admin:
       notify:
        mail:
         to: huenbin@foxmail.com
         from: enhinck@163.com
  mail:
   host: smtp.163.com
   username: enhinck@163.com
   password: 1234
   properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true
       required: true
